---

- name: install dnf-automatic
  dnf:
    name: dnf-automatic
    state: present

- name: configure dnf-automatic
  template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: 0644

- name: start and enable systemd timer for dnf-automatic
  service:
    name: dnf-automatic.timer
    state: started
    enabled: yes
  when: not ansible_check_mode
