---
- include_tasks: centos7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 7
    - use_classyllama_autoupdate | bool


- include_tasks: centos8.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int >= 8
    - use_classyllama_autoupdate | bool
